### ISSUE TITLE
In terms of algorithm implementation, what are the similarities and differences between the Boxy dataset and the Kitti dataset

### ISSUE THREAD

**Issue by WSTao** [thilius/3D_BBOX_from_2D#1]
The Boxy dataset is a pseudo 3D annotation. The 3D box of the kitti data set is obtained through lidar labeling box mapping. The 3D boxes obtained by these two Datasets are different, so how to deal with the algorithm

**Comment by thilius** [comment]
@WSTao Both the algorithms have their own train.py. The BOXY dataset should firstly be transfromed with the boxy2dataset.py. Then train with the train.py.

Regarding the different annotation, beside the pseudo annotation, the boxy dataset has only the annotation of the vehicles in the same direction. 

The 3D bbox prediction is based on the 2D object detection algorithm, in bbox_3d_prediction.py the YOLOv4 darknet is used.

**Comment by WSTao** [comment]
OK, Thanks
